import os

START_DATE = os.environ["START_DATE"] or "20200101"
END_DATE = os.environ["END_DATE"] or "20201231"
TIMEZONE = os.environ["TIMEZONE"] or "seoul/asia"

TWITTER_CONSUMER_KEY = os.environ["TWITTER_CONSUMER_KEY"]
TWITTER_CONSUMER_SECRET = os.environ["TWITTER_CONSUMER_SECRET"]
TWITTER_ACCESS_TOKEN_KEY = os.environ["TWITTER_ACCESS_TOKEN_KEY"]
TWITTER_ACCESS_TOKEN_SECRET = os.environ["TWITTER_ACCESS_TOKEN_SECRET"]
